version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:latest

    working_directory: ~/impala-rb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            gem install bundler
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: run tests
          command: |
            echo 'export CI=true'
            bundle exec rspec

      - store_artifacts:
          path: coverage
